### ISSUE TITLE
Code | Pyramid Pattern 1

### ISSUE THREAD

**Issue by aryashah2k** [openAOD/Java-PatternHouse#13]

**Comment by KashyapB02** [comment]
@aryashah2k  Can you please assign me all the issues for pyramid pattern(from 1 - 93, excluding those which are already been assigned) ??

**Comment by aryashah2k** [comment]
Okay sure, but please be sure if you will be able to do all. Also you can make PRs for 10, 20, 30 and 40 patterns for corresponding SWOC Scores mentioned by me in the swoc channel for patternhouse

**Comment by KashyapB02** [comment]
> Okay sure, but please be sure if you will be able to do all. Also you can make PRs for 10, 20, 30 and 40 patterns for corresponding SWOC Scores mentioned by me in the swoc channel for patternhouse

How much time will I get to finish all these issues?? Can you please provide a deadline time.

**Comment by aryashah2k** [comment]
SWOC says that not more than one week after assigning of issues. If 7 days pass I have to reassign to someone else. Do read the guidelines documents for participants sent by SWOC on the discord channel
